# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1785556fed94cae283f149651e063a20fa578ad6dfb1474d2c1262a5fecd9c924f70d9d49306b69e9b0f3f9c7d07263f2b935898d9d90c98802168c988fe0dc

test:
  secret_key_base: 3b18e2256079ec8b75b99dfa27dae29ef0405aa1f2aa92d37289753ce6f264c3ec48e5003bb9f3938cabbae6e2706329b6de64f18f38aba636d495f113a207b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
